package calendarx

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func WriteICS(path string, feed Feed, generatedAt time.Time) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(BuildICS(feed, generatedAt)), 0o644)
}

func BuildICS(feed Feed, generatedAt time.Time) string {
	events := append([]Event(nil), feed.Events...)
	sort.Slice(events, func(i, j int) bool {
		if events[i].Date == events[j].Date {
			return events[i].Symbol < events[j].Symbol
		}
		return events[i].Date < events[j].Date
	})

	var b strings.Builder
	writeLine(&b, "BEGIN:VCALENDAR")
	writeLine(&b, "VERSION:2.0")
	writeLine(&b, "PRODID:-//CalendarX//%s//EN", feed.Slug)
	writeLine(&b, "CALSCALE:GREGORIAN")
	writeLine(&b, "METHOD:PUBLISH")
	writeLine(&b, "X-WR-CALNAME:%s", escapeText(feed.Title+" Earnings"))
	writeLine(&b, "X-WR-CALDESC:%s", escapeText(feed.Description))

	stamp := generatedAt.UTC().Format("20060102T150405Z")
	for _, event := range events {
		writeLine(&b, "BEGIN:VEVENT")
		writeLine(&b, "UID:%s", escapeText(fmt.Sprintf("%s-%s-%s@calendarx", feed.Slug, event.Symbol, event.Date)))
		writeLine(&b, "DTSTAMP:%s", stamp)
		writeLine(&b, "DTSTART;VALUE=DATE:%s", CompactDate(event.Date))
		writeLine(&b, "DTEND;VALUE=DATE:%s", NextDateCompact(event.Date))
		writeLine(&b, "SUMMARY:%s", escapeText(summary(event)))
		writeLine(&b, "DESCRIPTION:%s", escapeText(description(event)))
		writeLine(&b, "TRANSP:TRANSPARENT")
		writeLine(&b, "STATUS:CONFIRMED")
		writeLine(&b, "END:VEVENT")
	}

	writeLine(&b, "END:VCALENDAR")
	return b.String()
}

func summary(event Event) string {
	suffix := ""
	if event.Time != "" {
		suffix = " (" + event.Time + ")"
	}
	return fmt.Sprintf("%s %s%s earnings", event.Symbol, event.CompanyName, suffix)
}

func description(event Event) string {
	lines := []string{
		"Company: " + event.CompanyName,
		"Symbol: " + event.Symbol,
	}
	if event.Industry != "" {
		lines = append(lines, "Industry: "+event.Industry)
	}
	if event.FiscalQuarterEnding != "" {
		lines = append(lines, "Fiscal quarter ending: "+event.FiscalQuarterEnding)
	}
	if event.EPSForecast != "" {
		lines = append(lines, "EPS forecast: "+event.EPSForecast)
	}
	if event.NoOfEsts != "" {
		lines = append(lines, "Estimate count: "+event.NoOfEsts)
	}
	if event.MarketCap != "" && event.MarketCap != "N/A" {
		lines = append(lines, "Market cap: "+event.MarketCap)
	}
	if event.Time != "" {
		lines = append(lines, "Reporting time: "+event.Time)
	}
	lines = append(lines,
		"",
		"Yahoo Finance: https://finance.yahoo.com/quote/"+event.Symbol,
		"Stocks app: stocks://?symbol="+event.Symbol,
		"",
		"Generated by CalendarX.",
	)
	return strings.Join(lines, "\n")
}

func escapeText(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, "\n", `\n`)
	value = strings.ReplaceAll(value, ";", `\;`)
	value = strings.ReplaceAll(value, ",", `\,`)
	return value
}

func writeLine(b *strings.Builder, format string, args ...any) {
	line := fmt.Sprintf(format, args...)
	for _, folded := range foldLine(line) {
		b.WriteString(folded)
		b.WriteString("\r\n")
	}
}

func foldLine(line string) []string {
	const limit = 75
	if len(line) <= limit {
		return []string{line}
	}
	var out []string
	remaining := line
	for len(remaining) > limit {
		out = append(out, remaining[:limit])
		remaining = " " + remaining[limit:]
	}
	out = append(out, remaining)
	return out
}
